<?php

namespace Salute\WelcomeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use \PDO;

/**
 * SamuraiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SamuraiRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        $samurai= $this->getEntityManager()
            ->createQuery('SELECT p FROM SaluteWelcomeBundle:Samurai p ORDER BY p.name DESC')
            ->getResult();
        foreach($samurai as $one){
            $sam['name']= $one->getName();
            $sam['skill']= $one->getSkill();
           if ($one->getAdvancedPhp() !== NULL){
                $sam['course'] =  $one->getAdvancedPhp()->getName();
            }else {$sam['course']='without cours';}
            $samurai_with_course[]= $sam;
        }

        return $samurai_with_course;
    }
}
