<?php

namespace Salute\WelcomeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * SamuraiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SamuraiRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
//        $qb = $this
//            ->createQueryBuilder('s')
//            ->leftJoin('s.advancedphp', 'g')
//            ->orderBy('s.name', 'DESC')
//        ;
//
//        return $qb
//            ->getQuery()
//            ->setFetchMode('Salute\WelcomeBundle\Entity\Samurai', 'advancedphp', ClassMetadata::FETCH_EAGER)
//            ->execute()
//        ;

//        $samurai= $this->getEntityManager()
//            ->createQuery('SELECT p FROM SaluteWelcomeBundle:Samurai p ORDER BY p.name DESC')
//            ->getResult();
//        foreach($samurai as /$one){
//            $sam['name']= $one->getName();
//            $sam['skill']= $one->getSkill();
//            if ($one->getAdvancedPhp() !== null){
//                $sam['course'] =  $one->getAdvancedPhp()->getName();
//            } else {
//                $sam['course']='without cours';
//            }
//            $samurai_with_course[]= $sam;
//        }
//
//        return $samurai_with_course;
//        $samurai = $this->getDoctrine()->getRepository('Salute\WelcomeBundle\Samurai')
//        ->findBy([], ['name'=>'asc']);
//
//        return $samurai;
   }

}
